package hackstreet.sixeswild.gui;

import hackstreet.sixeswild.game.SixesWild;

/**
 * 
 * @author Nicholas
 *
 */
public class SixesWildApplication {
	
	/** Game model. */
	SixesWild model;
	
	/** Main Screen GUI. */
	SWMainScreen mainScreen;
	
	/** Level selection screen GUI. */
	LevelSelectScreen levelSelectScreen;
	
	/** Achievement screen GUI. */
	AchievementScreen achievementScreen;
	
	/** Screen generated by the current active game. */
	ActiveGameScreen activeGameScreen;
	
	/** Current screen being displayed by the user. */
	AbstractScreen activeScreen;
	
	/**
	 * 
	 * @param model is the SixesWild
	 */
	public SixesWildApplication(SixesWild model){
		this.model = model;
	}
	
	/**
	 * Display MainScreen in main frame.
	 * @return true on success
	 */
	public void enterMainScreen(){
		this.activeScreen = this.mainScreen;
	}
	
	/**
	 * Display LevelSelectScreen in main frame.
	 * @return true on success
	 */
	public void enterLevelSelectScreen(){
		this.activeScreen = this.levelSelectScreen;
	}
	
	/**
	 * Display AchievementScreen in main frame.
	 * @return true on success
	 */
	public void enterAchievementScreen(){
		this.activeScreen = this.achievementScreen;
	}
	
	/**
	 * Display GameScreen in main frame.
	 * @return true on success
	 */
	public void enterGameScreen(){
		this.activeScreen = this.activeGameScreen;
	}
	
}
